### PR TITLE
Update to the dutch translations

### PR DESCRIPTION
**Pull request by jadenmeijer99**
Fixed a coupple of grammatical errors

### CODE REVIEW

**Comment by amadornes** [comment]
Mind updating? Apparently merging the other dutch PR broke yours :/

**Comment by jadenmeijer99** [comment]
I think I updated it now.

**Comment by amadornes** [comment]
GitHub still complains 😕

**Comment by jadenmeijer99** [comment]
I will just make a new pull request, maybe that helps.

**Pull request closed without merging**
